import type { AutomationBlueprint } from "@/types/automation";

const fullObservability = { tracing: true, metrics: true, logging: true, alerting: true };

export const automationRegistry: AutomationBlueprint[] = [
  {
    id: "lead_created",
    domain: "lead_operations",
    name: "Lead Created",
    description: "Captures new demand, creates follow-up priority, and feeds revenue recovery attribution.",
    triggers: ["lead form submitted", "audit requested", "booking intent detected"],
    emittedEvents: ["operational_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.lead_created", "intelligence.lead_scoring", "notification.lead_alert"],
    actions: ["persist lead", "score urgency", "notify operations", "queue follow-up"],
    intelligenceOutputs: ["lead source quality", "conversion probability", "follow-up urgency"],
    aliceGroundingSurfaces: ["lead attribution", "conversion history", "follow-up outcomes", "booking intent"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 5,
    requiredEnv: ["SUPABASE_SERVICE_ROLE_KEY"],
    observability: fullObservability
  },
  {
    id: "recall_due",
    domain: "recall",
    name: "Recall Due",
    description: "Detects overdue recall patients and coordinates recovery prioritization.",
    triggers: ["recall date reached", "hygiene inactivity detected", "retention threshold breached"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "orchestration_events", "intelligence_events"],
    queueHandlers: ["ingestion.recall_due", "forecasting.retention_risk", "recommendation.recall_recovery"],
    actions: ["segment patient", "prioritize outreach", "estimate recovery value", "queue operator review"],
    intelligenceOutputs: ["recall recovery rate", "retention risk", "hygiene utilization impact"],
    aliceGroundingSurfaces: ["recall history", "retention outcomes", "forecast drift", "benchmark rank"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "appointment_no_show",
    domain: "scheduling",
    name: "Appointment No-Show",
    description: "Routes missed appointments into recovery, forecast validation, and scheduling intelligence.",
    triggers: ["appointment marked no-show", "high no-show probability", "unconfirmed appointment expired"],
    emittedEvents: ["operational_events", "anomaly_events", "forecast_events", "orchestration_events", "replay_events", "intelligence_events"],
    queueHandlers: ["ingestion.appointment_no_show", "forecasting.no_show_risk", "orchestration.schedule_recovery"],
    actions: ["record missed visit", "calculate revenue leakage", "update patient risk", "queue recovery path"],
    intelligenceOutputs: ["no-show probability", "recovered appointments", "revenue saved", "reminder effectiveness"],
    aliceGroundingSurfaces: ["scheduling behavior", "confirmation history", "patient risk", "revenue impact"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 10,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "unpaid_invoice_detected",
    domain: "billing",
    name: "Unpaid Invoice Detected",
    description: "Identifies unresolved balances and routes revenue recovery with audit-safe follow-up.",
    triggers: ["invoice overdue", "balance aging threshold reached", "payment promise missed"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.unpaid_invoice", "recommendation.billing_recovery", "notification.billing_review"],
    actions: ["classify balance", "estimate recovery probability", "queue follow-up", "update revenue exposure"],
    intelligenceOutputs: ["billing recovery value", "aging risk", "collection probability"],
    aliceGroundingSurfaces: ["invoice history", "payment behavior", "revenue exposure", "follow-up outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    dependencies: ["billing_sync"],
    observability: fullObservability
  },
  {
    id: "missed_call_detected",
    domain: "front_office",
    name: "Missed Call Detected",
    description: "Turns missed calls into measurable front-office recovery and conversion intelligence.",
    triggers: ["missed call", "after-hours call", "unreturned voicemail"],
    emittedEvents: ["operational_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.missed_call", "recommendation.front_office_recovery", "notification.call_back_alert"],
    actions: ["record call", "rank urgency", "notify front desk", "track callback outcome"],
    intelligenceOutputs: ["response latency", "lost demand risk", "callback conversion"],
    aliceGroundingSurfaces: ["call history", "response latency", "booking outcome", "staffing pressure"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 15,
    observability: fullObservability
  },
  {
    id: "review_request_due",
    domain: "reputation",
    name: "Review Request Due",
    description: "Optimizes review request timing and measures reputation growth velocity.",
    triggers: ["appointment completed", "positive engagement detected", "review window reached"],
    emittedEvents: ["operational_events", "recommendation_events", "benchmark_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.visit_completed", "recommendation.review_timing", "notification.review_request"],
    actions: ["select review timing", "send request", "track conversion", "update benchmark position"],
    intelligenceOutputs: ["review conversion", "timing effectiveness", "sentiment trend", "benchmark movement"],
    aliceGroundingSurfaces: ["review history", "sentiment signal", "conversion trend", "benchmark rank"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    observability: fullObservability
  },
  {
    id: "stale_patient_detected",
    domain: "patient_followup",
    name: "Stale Patient Detected",
    description: "Detects declining engagement and queues retention recovery before churn accelerates.",
    triggers: ["engagement decline", "inactive window exceeded", "missed follow-up"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["ingestion.patient_stale", "forecasting.churn_risk", "recommendation.retention_path"],
    actions: ["score churn risk", "select recovery path", "queue staff review", "track reactivation"],
    intelligenceOutputs: ["churn probability", "retention effectiveness", "patient lifetime value risk"],
    aliceGroundingSurfaces: ["engagement history", "retention outcomes", "recovery path", "forecast confidence"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "reactivation_candidate_detected",
    domain: "patient_followup",
    name: "Reactivation Candidate Detected",
    description: "Identifies inactive patients with strong recovery probability and measurable revenue potential.",
    triggers: ["patient inactive", "treatment plan dormant", "recall recovery opportunity"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "orchestration_events", "intelligence_events"],
    queueHandlers: ["ingestion.reactivation_candidate", "recommendation.reactivation_priority", "orchestration.patient_recovery"],
    actions: ["estimate recovery value", "rank outreach priority", "queue approval", "measure outcome"],
    intelligenceOutputs: ["reactivation probability", "recoverable revenue", "retention lift"],
    aliceGroundingSurfaces: ["inactive segment", "treatment value", "outreach outcome", "benchmark context"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 240,
    observability: fullObservability
  },
  {
    id: "failed_payment_detected",
    domain: "billing",
    name: "Failed Payment Detected",
    description: "Routes failed payments into recovery with secure context and confidence-calibrated remediation.",
    triggers: ["payment failed", "card expired", "processor unavailable"],
    emittedEvents: ["operational_events", "anomaly_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.failed_payment", "recommendation.payment_recovery", "notification.billing_alert"],
    actions: ["classify failure", "queue retry", "notify billing", "track recovery"],
    intelligenceOutputs: ["payment recovery rate", "failure category", "revenue exposure"],
    aliceGroundingSurfaces: ["payment status", "failure history", "recovery outcome", "revenue exposure"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    requiredEnv: ["SUPABASE_SERVICE_ROLE_KEY"],
    observability: fullObservability
  },
  {
    id: "ai_followup_required",
    domain: "mission_control",
    name: "ALICE Follow-Up Required",
    description: "Escalates unresolved intelligence items into operator-visible remediation plans.",
    triggers: ["critical anomaly", "forecast drift", "recommendation unresolved", "queue degradation"],
    emittedEvents: ["intelligence_events", "orchestration_events", "recommendation_events", "replay_events", "anomaly_events"],
    queueHandlers: ["intelligence.alice_followup", "orchestration.operator_review", "recommendation.remediation_plan"],
    actions: ["summarize issue", "rank severity", "suggest remediation", "track operator decision"],
    intelligenceOutputs: ["operational summary", "remediation plan", "confidence movement", "decision history"],
    aliceGroundingSurfaces: ["trace history", "dead letters", "forecast drift", "recommendation lineage", "operator decisions"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 20,
    observability: fullObservability
  },
  {
    id: "treatment_recovery",
    domain: "patient_followup",
    name: "Treatment Recovery",
    description: "Identifies unscheduled treatment plans, educates patients, and tracks acceptance recovery.",
    triggers: ["unscheduled treatment detected", "treatment plan stale", "provider follow-up requested"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "intelligence_events"],
    queueHandlers: ["ingestion.treatment_plan_stale", "recommendation.treatment_recovery", "orchestration.treatment_followup"],
    actions: ["segment open treatment", "send education sequence", "queue follow-up reminders", "measure acceptance"],
    intelligenceOutputs: ["treatment acceptance lift", "production recovered", "follow-up effectiveness"],
    aliceGroundingSurfaces: ["treatment plan value", "patient response", "provider notes", "acceptance outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "referral_growth",
    domain: "marketing",
    name: "Referral Growth",
    description: "Finds promoter patients, launches referral outreach, and attributes referral revenue.",
    triggers: ["promoter detected", "positive review completed", "referral campaign requested"],
    emittedEvents: ["operational_events", "recommendation_events", "benchmark_events", "intelligence_events"],
    queueHandlers: ["ingestion.promoter_detected", "recommendation.referral_growth", "campaign.referral_launch"],
    actions: ["identify promoters", "launch referral campaign", "track referral source", "measure referral revenue"],
    intelligenceOutputs: ["referral conversion", "referral revenue", "promoter segment performance"],
    aliceGroundingSurfaces: ["review sentiment", "patient value", "referral source", "conversion outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    observability: fullObservability
  },
  {
    id: "schedule_gap_fill",
    domain: "scheduling",
    name: "Schedule Gap Fill",
    description: "Detects schedule openings, finds eligible patients, and launches targeted booking offers.",
    triggers: ["schedule opening detected", "provider capacity available", "gap fill requested"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "orchestration_events"],
    queueHandlers: ["ingestion.schedule_gap", "forecasting.capacity_match", "orchestration.gap_fill"],
    actions: ["detect openings", "match eligible patients", "send booking offers", "track filled appointments"],
    intelligenceOutputs: ["chair utilization lift", "filled appointment count", "revenue saved"],
    aliceGroundingSurfaces: ["schedule availability", "patient eligibility", "booking response", "provider capacity"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 15,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "recall_capacity_optimization",
    domain: "scheduling",
    name: "Recall Capacity Optimization",
    description: "Balances recall outreach against provider availability to avoid overloading the schedule.",
    triggers: ["recall load exceeds capacity", "provider availability changed", "capacity balancing requested"],
    emittedEvents: ["forecast_events", "operational_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["forecasting.recall_capacity", "recommendation.capacity_balance", "orchestration.recall_throttle"],
    actions: ["forecast provider availability", "balance recall outreach", "throttle campaigns", "measure utilization"],
    intelligenceOutputs: ["capacity balance score", "recall load risk", "utilization lift"],
    aliceGroundingSurfaces: ["provider schedule", "recall backlog", "campaign response", "utilization outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "alice_revenue_opportunity_agent",
    domain: "ai",
    name: "ALICE Revenue Opportunity Agent",
    description: "Detects revenue leakage, calculates opportunity value, recommends recovery workflows, and launches approved actions.",
    triggers: ["revenue risk detected", "assessment completed", "forecast drift detected"],
    emittedEvents: ["intelligence_events", "recommendation_events", "forecast_events", "orchestration_events"],
    queueHandlers: ["ai.revenue_opportunity", "recommendation.workflow_selection", "orchestration.revenue_recovery"],
    actions: ["detect leakage", "calculate opportunity value", "recommend workflow", "track outcome"],
    intelligenceOutputs: ["revenue risk score", "recommended workflow", "expected recovery"],
    aliceGroundingSurfaces: ["roi calculations", "forecast drift", "runtime outcomes", "benchmark context"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 20,
    observability: fullObservability
  },
  {
    id: "alice_practice_health_agent",
    domain: "ai",
    name: "ALICE Practice Health Agent",
    description: "Monitors composite health signals and turns declining metrics into prioritized recommendations.",
    triggers: ["practice health declined", "weekly executive review", "critical metric breached"],
    emittedEvents: ["intelligence_events", "recommendation_events", "operational_events"],
    queueHandlers: ["ai.practice_health", "recommendation.health_priority", "orchestration.operator_review"],
    actions: ["score health", "identify declining metrics", "prioritize recommendation", "track decision"],
    intelligenceOutputs: ["practice health score", "priority recommendation", "health trend"],
    aliceGroundingSurfaces: ["practice health score", "operational metrics", "workflow outcomes", "tenant benchmarks"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    observability: fullObservability
  },
  {
    id: "alice_growth_agent",
    domain: "ai",
    name: "ALICE Growth Agent",
    description: "Monitors reviews, referrals, and lead conversion to recommend and launch growth campaigns.",
    triggers: ["review velocity declined", "referral opportunity detected", "lead nurture gap detected"],
    emittedEvents: ["intelligence_events", "recommendation_events", "benchmark_events", "orchestration_events"],
    queueHandlers: ["ai.growth_monitor", "recommendation.growth_campaign", "campaign.growth_launch"],
    actions: ["monitor growth signals", "recommend campaign", "launch approved workflow", "measure conversion"],
    intelligenceOutputs: ["growth score", "campaign recommendation", "conversion lift"],
    aliceGroundingSurfaces: ["review conversion", "referral history", "lead funnel", "campaign outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 45,
    observability: fullObservability
  },
  {
    id: "welcome_patient",
    domain: "patient_influence",
    name: "Welcome Patient Video Journey",
    description: "Launches welcome video journeys for new patient readiness and first-visit attendance.",
    triggers: ["new patient appointment scheduled", "lead converted to patient"],
    emittedEvents: ["video.generated", "video.sent", "video.opened", "video.viewed", "video.completed", "video.cta_clicked"],
    queueHandlers: ["video.welcome_patient", "n8n.video_delivery", "intelligence.attention_score"],
    actions: ["classify journey", "select video", "deliver video", "write evidence", "attribute outcome"],
    intelligenceOutputs: ["attention score", "attendance probability", "best channel"],
    aliceGroundingSurfaces: ["appointment event", "video engagement", "patient score", "mission control outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  ...[
    ["video_confirmation", "Confirmation Video Journey", "appointment requires confirmation"],
    ["video_reminder", "Reminder Video Journey", "appointment reminder window reached"],
    ["video_recall", "Recall Video Journey", "recall due"],
    ["video_reactivation", "Reactivation Video Journey", "inactive patient over 12 months"],
    ["video_no_show_recovery", "No Show Recovery Video Journey", "appointment marked no-show"],
    ["video_post_visit", "Post Visit Recovery Video Journey", "procedure completed"],
    ["video_review_request", "Review Growth Video Journey", "satisfied patient detected"],
    ["video_referral_request", "Referral Growth Video Journey", "promoter patient detected"],
    ["video_membership", "Membership Enrollment Video Journey", "membership eligible patient detected"],
    ["video_treatment_acceptance", "Treatment Acceptance Video Journey", "treatment plan created"],
    ["video_vip_loyalty", "VIP Loyalty Video Journey", "high value patient loyalty moment"]
  ].map(([id, name, trigger]) => ({
    id,
    domain: "patient_influence" as const,
    name,
    description: `${name} selects the right patient journey video, tracks engagement, writes evidence, and attributes outcomes.`,
    triggers: [trigger],
    emittedEvents: ["video.generated", "video.sent", "video.opened", "video.viewed", "video.completed", "video.cta_clicked"],
    queueHandlers: [`video.${id}`, "n8n.video_delivery", "intelligence.video_recommendation"],
    actions: ["classify patient journey", "select video", "deliver video", "track engagement", "write attribution"],
    intelligenceOutputs: ["best send time", "best channel", "best journey", "expected revenue impact", "confidence score"],
    aliceGroundingSurfaces: ["patient journey", "delivery record", "engagement record", "revenue attribution", "mission control outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  }))
];

export function getAutomationBlueprint(id: string) {
  return automationRegistry.find(blueprint => blueprint.id === id);
}
