import type { AutomationBlueprint } from "@/types/automation";

const fullObservability = { tracing: true, metrics: true, logging: true, alerting: true };

export const automationRegistry: AutomationBlueprint[] = [
  {
    id: "lead_created",
    domain: "lead_operations",
    name: "Lead Created",
    description: "Captures new demand, creates follow-up priority, and feeds revenue recovery attribution.",
    triggers: ["lead form submitted", "audit requested", "booking intent detected"],
    emittedEvents: ["operational_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.lead_created", "intelligence.lead_scoring", "notification.lead_alert"],
    actions: ["persist lead", "score urgency", "notify operations", "queue follow-up"],
    intelligenceOutputs: ["lead source quality", "conversion probability", "follow-up urgency"],
    aliceGroundingSurfaces: ["lead attribution", "conversion history", "follow-up outcomes", "booking intent"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 5,
    requiredEnv: ["SUPABASE_SERVICE_ROLE_KEY"],
    observability: fullObservability
  },
  {
    id: "recall_due",
    domain: "recall",
    name: "Recall Due",
    description: "Detects overdue recall patients and coordinates recovery prioritization.",
    triggers: ["recall date reached", "hygiene inactivity detected", "retention threshold breached"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "orchestration_events", "intelligence_events"],
    queueHandlers: ["ingestion.recall_due", "forecasting.retention_risk", "recommendation.recall_recovery"],
    actions: ["segment patient", "prioritize outreach", "estimate recovery value", "queue operator review"],
    intelligenceOutputs: ["recall recovery rate", "retention risk", "hygiene utilization impact"],
    aliceGroundingSurfaces: ["recall history", "retention outcomes", "forecast drift", "benchmark rank"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "appointment_created",
    domain: "scheduling",
    name: "Appointment Created",
    description: "Confirms new bookings, attaches attribution, and starts pre-visit engagement.",
    triggers: ["calendly booking received", "PMS appointment created", "booking form submitted"],
    emittedEvents: ["operational_events", "orchestration_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.appointment_created", "orchestration.pre_visit_journey", "notification.booking_confirmation"],
    actions: ["persist booking", "link lead attribution", "send confirmation", "queue pre-visit journey"],
    intelligenceOutputs: ["booking source quality", "show probability", "pre-visit readiness"],
    aliceGroundingSurfaces: ["booking history", "lead attribution", "confirmation outcome", "journey progress"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 5,
    observability: fullObservability
  },
  {
    id: "appointment_cancelled",
    domain: "scheduling",
    name: "Appointment Cancelled",
    description: "Captures cancellations, measures revenue at risk, and routes rebooking recovery.",
    triggers: ["calendly cancellation received", "PMS appointment cancelled", "patient cancellation request"],
    emittedEvents: ["operational_events", "anomaly_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.appointment_cancelled", "recommendation.rebooking_recovery", "notification.cancellation_alert"],
    actions: ["update booking status", "calculate revenue at risk", "queue rebooking outreach", "notify operations"],
    intelligenceOutputs: ["cancellation rate", "rebooking conversion", "revenue at risk"],
    aliceGroundingSurfaces: ["cancellation history", "rebooking outcomes", "patient risk", "schedule impact"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 10,
    observability: fullObservability
  },
  {
    id: "appointment_no_show",
    domain: "scheduling",
    name: "Appointment No-Show",
    description: "Routes missed appointments into recovery, forecast validation, and scheduling intelligence.",
    triggers: ["appointment marked no-show", "high no-show probability", "unconfirmed appointment expired"],
    emittedEvents: ["operational_events", "anomaly_events", "forecast_events", "orchestration_events", "replay_events", "intelligence_events"],
    queueHandlers: ["ingestion.appointment_no_show", "forecasting.no_show_risk", "orchestration.schedule_recovery"],
    actions: ["record missed visit", "calculate revenue leakage", "update patient risk", "queue recovery path"],
    intelligenceOutputs: ["no-show probability", "recovered appointments", "revenue saved", "reminder effectiveness"],
    aliceGroundingSurfaces: ["scheduling behavior", "confirmation history", "patient risk", "revenue impact"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 10,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "unpaid_invoice_detected",
    domain: "billing",
    name: "Unpaid Invoice Detected",
    description: "Identifies unresolved balances and routes revenue recovery with audit-safe follow-up.",
    triggers: ["invoice overdue", "balance aging threshold reached", "payment promise missed"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.unpaid_invoice", "recommendation.billing_recovery", "notification.billing_review"],
    actions: ["classify balance", "estimate recovery probability", "queue follow-up", "update revenue exposure"],
    intelligenceOutputs: ["billing recovery value", "aging risk", "collection probability"],
    aliceGroundingSurfaces: ["invoice history", "payment behavior", "revenue exposure", "follow-up outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    dependencies: ["billing_sync"],
    observability: fullObservability
  },
  {
    id: "missed_call_detected",
    domain: "front_office",
    name: "Missed Call Detected",
    description: "Turns missed calls into measurable front-office recovery and conversion intelligence.",
    triggers: ["missed call", "after-hours call", "unreturned voicemail"],
    emittedEvents: ["operational_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.missed_call", "recommendation.front_office_recovery", "notification.call_back_alert"],
    actions: ["record call", "rank urgency", "notify front desk", "track callback outcome"],
    intelligenceOutputs: ["response latency", "lost demand risk", "callback conversion"],
    aliceGroundingSurfaces: ["call history", "response latency", "booking outcome", "staffing pressure"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 15,
    observability: fullObservability
  },
  {
    id: "review_request_due",
    domain: "reputation",
    name: "Review Request Due",
    description: "Optimizes review request timing and measures reputation growth velocity.",
    triggers: ["appointment completed", "positive engagement detected", "review window reached"],
    emittedEvents: ["operational_events", "recommendation_events", "benchmark_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.visit_completed", "recommendation.review_timing", "notification.review_request"],
    actions: ["select review timing", "send request", "track conversion", "update benchmark position"],
    intelligenceOutputs: ["review conversion", "timing effectiveness", "sentiment trend", "benchmark movement"],
    aliceGroundingSurfaces: ["review history", "sentiment signal", "conversion trend", "benchmark rank"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    observability: fullObservability
  },
  {
    id: "stale_patient_detected",
    domain: "patient_followup",
    name: "Stale Patient Detected",
    description: "Detects declining engagement and queues retention recovery before churn accelerates.",
    triggers: ["engagement decline", "inactive window exceeded", "missed follow-up"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["ingestion.patient_stale", "forecasting.churn_risk", "recommendation.retention_path"],
    actions: ["score churn risk", "select recovery path", "queue staff review", "track reactivation"],
    intelligenceOutputs: ["churn probability", "retention effectiveness", "patient lifetime value risk"],
    aliceGroundingSurfaces: ["engagement history", "retention outcomes", "recovery path", "forecast confidence"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "reactivation_candidate_detected",
    domain: "patient_followup",
    name: "Reactivation Candidate Detected",
    description: "Identifies inactive patients with strong recovery probability and measurable revenue potential.",
    triggers: ["patient inactive", "treatment plan dormant", "recall recovery opportunity"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "orchestration_events", "intelligence_events"],
    queueHandlers: ["ingestion.reactivation_candidate", "recommendation.reactivation_priority", "orchestration.patient_recovery"],
    actions: ["estimate recovery value", "rank outreach priority", "queue approval", "measure outcome"],
    intelligenceOutputs: ["reactivation probability", "recoverable revenue", "retention lift"],
    aliceGroundingSurfaces: ["inactive segment", "treatment value", "outreach outcome", "benchmark context"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 240,
    observability: fullObservability
  },
  {
    id: "failed_payment_detected",
    domain: "billing",
    name: "Failed Payment Detected",
    description: "Routes failed payments into recovery with secure context and confidence-calibrated remediation.",
    triggers: ["payment failed", "card expired", "processor unavailable"],
    emittedEvents: ["operational_events", "anomaly_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["ingestion.failed_payment", "recommendation.payment_recovery", "notification.billing_alert"],
    actions: ["classify failure", "queue retry", "notify billing", "track recovery"],
    intelligenceOutputs: ["payment recovery rate", "failure category", "revenue exposure"],
    aliceGroundingSurfaces: ["payment status", "failure history", "recovery outcome", "revenue exposure"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    requiredEnv: ["SUPABASE_SERVICE_ROLE_KEY"],
    observability: fullObservability
  },
  {
    id: "ai_followup_required",
    domain: "mission_control",
    name: "ALICE Follow-Up Required",
    description: "Escalates unresolved intelligence items into operator-visible remediation plans.",
    triggers: ["critical anomaly", "forecast drift", "recommendation unresolved", "queue degradation"],
    emittedEvents: ["intelligence_events", "orchestration_events", "recommendation_events", "replay_events", "anomaly_events"],
    queueHandlers: ["intelligence.alice_followup", "orchestration.operator_review", "recommendation.remediation_plan"],
    actions: ["summarize issue", "rank severity", "suggest remediation", "track operator decision"],
    intelligenceOutputs: ["operational summary", "remediation plan", "confidence movement", "decision history"],
    aliceGroundingSurfaces: ["trace history", "dead letters", "forecast drift", "recommendation lineage", "operator decisions"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 20,
    observability: fullObservability
  },
  {
    id: "treatment_recovery",
    domain: "patient_followup",
    name: "Treatment Recovery",
    description: "Identifies unscheduled treatment plans, educates patients, and tracks acceptance recovery.",
    triggers: ["unscheduled treatment detected", "treatment plan stale", "provider follow-up requested"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "intelligence_events"],
    queueHandlers: ["ingestion.treatment_plan_stale", "recommendation.treatment_recovery", "orchestration.treatment_followup"],
    actions: ["segment open treatment", "send education sequence", "queue follow-up reminders", "measure acceptance"],
    intelligenceOutputs: ["treatment acceptance lift", "production recovered", "follow-up effectiveness"],
    aliceGroundingSurfaces: ["treatment plan value", "patient response", "provider notes", "acceptance outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "referral_growth",
    domain: "marketing",
    name: "Referral Growth",
    description: "Finds promoter patients, launches referral outreach, and attributes referral revenue.",
    triggers: ["promoter detected", "positive review completed", "referral campaign requested"],
    emittedEvents: ["operational_events", "recommendation_events", "benchmark_events", "intelligence_events"],
    queueHandlers: ["ingestion.promoter_detected", "recommendation.referral_growth", "campaign.referral_launch"],
    actions: ["identify promoters", "launch referral campaign", "track referral source", "measure referral revenue"],
    intelligenceOutputs: ["referral conversion", "referral revenue", "promoter segment performance"],
    aliceGroundingSurfaces: ["review sentiment", "patient value", "referral source", "conversion outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    observability: fullObservability
  },
  {
    id: "schedule_gap_fill",
    domain: "scheduling",
    name: "Schedule Gap Fill",
    description: "Detects schedule openings, finds eligible patients, and launches targeted booking offers.",
    triggers: ["schedule opening detected", "provider capacity available", "gap fill requested"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "orchestration_events"],
    queueHandlers: ["ingestion.schedule_gap", "forecasting.capacity_match", "orchestration.gap_fill"],
    actions: ["detect openings", "match eligible patients", "send booking offers", "track filled appointments"],
    intelligenceOutputs: ["chair utilization lift", "filled appointment count", "revenue saved"],
    aliceGroundingSurfaces: ["schedule availability", "patient eligibility", "booking response", "provider capacity"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 15,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "recall_capacity_optimization",
    domain: "scheduling",
    name: "Recall Capacity Optimization",
    description: "Balances recall outreach against provider availability to avoid overloading the schedule.",
    triggers: ["recall load exceeds capacity", "provider availability changed", "capacity balancing requested"],
    emittedEvents: ["forecast_events", "operational_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["forecasting.recall_capacity", "recommendation.capacity_balance", "orchestration.recall_throttle"],
    actions: ["forecast provider availability", "balance recall outreach", "throttle campaigns", "measure utilization"],
    intelligenceOutputs: ["capacity balance score", "recall load risk", "utilization lift"],
    aliceGroundingSurfaces: ["provider schedule", "recall backlog", "campaign response", "utilization outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "alice_revenue_opportunity_agent",
    domain: "ai",
    name: "ALICE Revenue Opportunity Agent",
    description: "Detects revenue leakage, calculates opportunity value, recommends recovery workflows, and launches approved actions.",
    triggers: ["revenue risk detected", "assessment completed", "forecast drift detected"],
    emittedEvents: ["intelligence_events", "recommendation_events", "forecast_events", "orchestration_events"],
    queueHandlers: ["ai.revenue_opportunity", "recommendation.workflow_selection", "orchestration.revenue_recovery"],
    actions: ["detect leakage", "calculate opportunity value", "recommend workflow", "track outcome"],
    intelligenceOutputs: ["revenue risk score", "recommended workflow", "expected recovery"],
    aliceGroundingSurfaces: ["roi calculations", "forecast drift", "runtime outcomes", "benchmark context"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 20,
    observability: fullObservability
  },
  {
    id: "alice_practice_health_agent",
    domain: "ai",
    name: "ALICE Practice Health Agent",
    description: "Monitors composite health signals and turns declining metrics into prioritized recommendations.",
    triggers: ["practice health declined", "weekly executive review", "critical metric breached"],
    emittedEvents: ["intelligence_events", "recommendation_events", "operational_events"],
    queueHandlers: ["ai.practice_health", "recommendation.health_priority", "orchestration.operator_review"],
    actions: ["score health", "identify declining metrics", "prioritize recommendation", "track decision"],
    intelligenceOutputs: ["practice health score", "priority recommendation", "health trend"],
    aliceGroundingSurfaces: ["practice health score", "operational metrics", "workflow outcomes", "tenant benchmarks"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    observability: fullObservability
  },
  {
    id: "alice_growth_agent",
    domain: "ai",
    name: "ALICE Growth Agent",
    description: "Monitors reviews, referrals, and lead conversion to recommend and launch growth campaigns.",
    triggers: ["review velocity declined", "referral opportunity detected", "lead nurture gap detected"],
    emittedEvents: ["intelligence_events", "recommendation_events", "benchmark_events", "orchestration_events"],
    queueHandlers: ["ai.growth_monitor", "recommendation.growth_campaign", "campaign.growth_launch"],
    actions: ["monitor growth signals", "recommend campaign", "launch approved workflow", "measure conversion"],
    intelligenceOutputs: ["growth score", "campaign recommendation", "conversion lift"],
    aliceGroundingSurfaces: ["review conversion", "referral history", "lead funnel", "campaign outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 45,
    observability: fullObservability
  },
  {
    id: "welcome_patient",
    domain: "patient_influence",
    name: "Welcome Patient Video Journey",
    description: "Delivers welcome, expectation-setting, and arrival videos for new patients while tracking attention and attendance.",
    triggers: ["new patient appointment scheduled", "lead converted to patient", "appointment T-14 window reached"],
    emittedEvents: ["operational_events", "orchestration_events", "intelligence_events", "recommendation_events"],
    queueHandlers: ["video.new_patient_journey", "n8n.video_delivery", "intelligence.attention_score"],
    actions: ["select welcome video", "deliver journey step", "track engagement", "recommend next best action"],
    intelligenceOutputs: ["attendance probability", "attention score", "arrival readiness"],
    aliceGroundingSurfaces: ["appointment type", "patient history", "video engagement", "journey outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "cleaning_journey",
    domain: "patient_influence",
    name: "Cleaning Video Journey",
    description: "Educates hygiene patients before visits and tracks confirmation, completion, and recall behavior.",
    triggers: ["cleaning appointment scheduled", "hygiene visit T-14 window reached", "preventive education requested"],
    emittedEvents: ["operational_events", "orchestration_events", "intelligence_events"],
    queueHandlers: ["video.cleaning_journey", "n8n.video_delivery", "intelligence.compliance_score"],
    actions: ["select preventive care video", "deliver reminder education", "track attendance", "update recall readiness"],
    intelligenceOutputs: ["attendance lift", "recall compliance signal", "patient attention score"],
    aliceGroundingSurfaces: ["recall history", "appointment compliance", "video completion", "patient lifecycle"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 45,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "treatment_acceptance_journey",
    domain: "patient_influence",
    name: "Treatment Acceptance Video Journey",
    description: "Orchestrates procedure education, benefits, financing, and success-story videos to increase treatment acceptance.",
    triggers: ["treatment plan created", "unscheduled treatment detected", "case acceptance risk detected"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["video.treatment_acceptance", "intelligence.conversion_profile", "n8n.video_delivery"],
    actions: ["select procedure education", "deliver financing video", "track scheduling CTA", "attribute accepted treatment"],
    intelligenceOutputs: ["treatment readiness", "expected revenue impact", "acceptance probability"],
    aliceGroundingSurfaces: ["treatment plan value", "patient engagement", "financing signal", "accepted outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "membership_enrollment_journey",
    domain: "patient_influence",
    name: "Membership Enrollment Video Journey",
    description: "Identifies membership-ready patients, sends benefits videos, and attributes enrollment revenue.",
    triggers: ["membership eligibility detected", "uninsured patient identified", "membership CTA clicked"],
    emittedEvents: ["operational_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["video.membership_enrollment", "intelligence.membership_readiness", "n8n.video_delivery"],
    actions: ["score eligibility", "send membership video", "track enrollment CTA", "attribute membership revenue"],
    intelligenceOutputs: ["membership readiness", "enrollment probability", "membership revenue impact"],
    aliceGroundingSurfaces: ["insurance status", "patient value", "video engagement", "membership outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "review_request_video",
    domain: "patient_influence",
    name: "Review Request Video Journey",
    description: "Uses provider-personalized video to convert satisfied patients into reviews with measurable velocity.",
    triggers: ["satisfied patient detected", "appointment completed", "positive engagement signal"],
    emittedEvents: ["operational_events", "benchmark_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["video.review_request", "n8n.video_delivery", "intelligence.review_conversion"],
    actions: ["select review video", "deliver Google review CTA", "track completion", "attribute reputation lift"],
    intelligenceOutputs: ["review readiness", "review conversion", "review velocity impact"],
    aliceGroundingSurfaces: ["visit outcome", "patient sentiment", "CTA click", "review submission"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 90,
    dependencies: ["n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "referral_request_video",
    domain: "patient_influence",
    name: "Referral Request Video Journey",
    description: "Finds promoter patients, sends referral videos, and tracks referral conversion and revenue influence.",
    triggers: ["promoter identified", "review submitted", "referral opportunity detected"],
    emittedEvents: ["operational_events", "benchmark_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["video.referral_request", "intelligence.promoter_profile", "n8n.video_delivery"],
    actions: ["identify promoter", "send referral video", "track referral CTA", "attribute referral revenue"],
    intelligenceOutputs: ["promoter readiness", "referral conversion", "referral revenue impact"],
    aliceGroundingSurfaces: ["review sentiment", "patient value", "referral CTA", "new patient outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    dependencies: ["n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "patient_30_day_checkin",
    domain: "patient_influence",
    name: "Patient 30 Day Video Check-In",
    description: "Sends post-visit check-in videos and routes engagement signals into retention, review, and referral actions.",
    triggers: ["visit completed 30 days ago", "post-visit relationship nurture due", "low engagement detected"],
    emittedEvents: ["operational_events", "orchestration_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["video.patient_30_day_checkin", "intelligence.retention_signal", "n8n.video_delivery"],
    actions: ["send check-in video", "score relationship", "recommend next action", "track retention outcome"],
    intelligenceOutputs: ["relationship score", "retention risk", "next best action"],
    aliceGroundingSurfaces: ["post-visit engagement", "review/referral history", "retention signal", "next action outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "financing_journey",
    domain: "patient_influence",
    name: "Financing Video Journey",
    description: "Delivers financing education when affordability blocks treatment acceptance and attributes recovered production.",
    triggers: ["financing concern detected", "high-value treatment unscheduled", "financing CTA requested"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["video.financing_journey", "intelligence.affordability_signal", "n8n.video_delivery"],
    actions: ["select financing video", "deliver CTA", "track scheduling", "attribute recovered production"],
    intelligenceOutputs: ["affordability signal", "financing conversion", "revenue influenced"],
    aliceGroundingSurfaces: ["treatment value", "financing engagement", "CTA click", "scheduled treatment"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  },
  {
    id: "recall_recovery",
    domain: "recall",
    name: "Recall Recovery",
    description:
      "IVY's tiered (6/12/18mo) recall-overdue recovery automation — segments patients by overdue tier and drives recall booking outreach.",
    triggers: ["recall.overdue (6mo tier)", "recall.overdue (12mo tier)", "recall.overdue (18mo tier)"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "intelligence_events"],
    queueHandlers: ["agent.ivy.recall_recovery", "recommendation.recall_recovery"],
    actions: ["segment by overdue tier", "prioritize outreach", "estimate recovery value", "queue recall booking"],
    intelligenceOutputs: ["recall recovery rate", "tier conversion", "retention risk"],
    aliceGroundingSurfaces: ["recall history", "retention outcomes", "tier performance"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    dependencies: ["open_dental_sync"],
    observability: fullObservability
  },
  {
    id: "treatment_acceptance",
    domain: "patient_followup",
    name: "Treatment Acceptance",
    description:
      "IVY's unscheduled/high-value treatment acceptance automation — proxies treatment-plan value off roi_calculations.recoverable_revenue until PMS treatment-plan data is connected (see lib/automation/detectors.ts detectUnscheduledTreatment).",
    triggers: ["treatment.unscheduled", "treatment.high_value"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "intelligence_events"],
    queueHandlers: ["agent.ivy.treatment_acceptance", "recommendation.treatment_recovery"],
    actions: ["segment unscheduled treatment", "prioritize high-value cases", "send education sequence", "measure acceptance"],
    intelligenceOutputs: ["treatment acceptance lift", "production recovered", "high-value conversion"],
    aliceGroundingSurfaces: ["treatment plan value", "patient engagement", "acceptance outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 120,
    observability: fullObservability
  },
  {
    id: "patient_reactivation",
    domain: "patient_followup",
    name: "Patient Reactivation",
    description: "IVY's inactive-patient reactivation automation — routes patient.inactive through ExecutionEngine for agent attribution.",
    triggers: ["patient.inactive"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["agent.ivy.patient_reactivation", "recommendation.reactivation_priority"],
    actions: ["score churn risk", "select recovery path", "queue reactivation outreach", "track reactivation"],
    intelligenceOutputs: ["churn probability", "reactivation probability", "recoverable revenue"],
    aliceGroundingSurfaces: ["engagement history", "inactive segment", "outreach outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    observability: fullObservability
  },
  {
    id: "claim_recovery",
    domain: "billing",
    name: "Claim Recovery",
    description:
      "FINN's tiered (30/60/90 day) aging-claim recovery automation, reading public.claims (added in migration 202606230001_finn_financial_tables.sql since no existing table represented dental insurance claims).",
    triggers: ["claim.aging.30", "claim.aging.60", "claim.aging.90"],
    emittedEvents: ["operational_events", "recommendation_events", "forecast_events", "intelligence_events"],
    queueHandlers: ["agent.finn.claim_recovery", "recommendation.billing_recovery"],
    actions: ["classify claim age", "estimate recovery probability", "escalate by tier", "queue payer follow-up"],
    intelligenceOutputs: ["claim recovery rate", "aging risk", "collection probability"],
    aliceGroundingSurfaces: ["claim history", "payer behavior", "revenue exposure"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    observability: fullObservability
  },
  {
    id: "balance_recovery",
    domain: "billing",
    name: "Balance Recovery",
    description: "FINN's overdue patient-balance recovery automation, reusing existing public.invoices rather than a new table.",
    triggers: ["balance.overdue"],
    emittedEvents: ["operational_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["agent.finn.balance_recovery", "notification.billing_review"],
    actions: ["classify balance", "estimate recovery probability", "queue follow-up", "update revenue exposure"],
    intelligenceOutputs: ["balance recovery value", "collection probability"],
    aliceGroundingSurfaces: ["invoice history", "payment behavior", "revenue exposure"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    observability: fullObservability
  },
  {
    id: "payment_recovery",
    domain: "billing",
    name: "Payment Recovery",
    description: "FINN's failed-payment recovery automation, reusing existing public.payment_attempts rather than a new table.",
    triggers: ["payment.failed"],
    emittedEvents: ["operational_events", "anomaly_events", "recommendation_events", "notification_events", "intelligence_events"],
    queueHandlers: ["agent.finn.payment_recovery", "notification.billing_alert"],
    actions: ["classify failure", "queue retry", "notify billing", "track recovery"],
    intelligenceOutputs: ["payment recovery rate", "failure category", "revenue exposure"],
    aliceGroundingSurfaces: ["payment status", "failure history", "recovery outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 30,
    observability: fullObservability
  },
  {
    id: "open_chair_recovery",
    domain: "scheduling",
    name: "Open Chair Recovery",
    description:
      "MAX's open-slot recovery automation — proxies open chair capacity off recent cancellations (no dedicated provider-schedule table exists; see lib/automation/detectors.ts detectOpenSlots comment).",
    triggers: ["schedule.open_slot"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "orchestration_events"],
    queueHandlers: ["agent.max.open_chair_recovery", "orchestration.gap_fill"],
    actions: ["detect openings", "match eligible patients", "send booking offers", "track filled appointments"],
    intelligenceOutputs: ["chair utilization lift", "filled appointment count", "revenue saved"],
    aliceGroundingSurfaces: ["schedule availability", "patient eligibility", "booking response"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 15,
    observability: fullObservability
  },
  {
    id: "waitlist_fill",
    domain: "scheduling",
    name: "Waitlist Fill",
    description: "MAX's schedule-gap-cluster waitlist fill automation — escalates clustered cancellations into waitlist outreach.",
    triggers: ["schedule.gap_detected"],
    emittedEvents: ["operational_events", "forecast_events", "recommendation_events", "orchestration_events"],
    queueHandlers: ["agent.max.waitlist_fill", "orchestration.waitlist_match"],
    actions: ["detect gap cluster", "match waitlist patients", "send fill offers", "track filled slots"],
    intelligenceOutputs: ["waitlist conversion", "gap fill rate", "revenue saved"],
    aliceGroundingSurfaces: ["schedule availability", "waitlist response", "provider capacity"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 15,
    observability: fullObservability
  },
  {
    id: "patient_advocacy",
    domain: "reputation",
    name: "Patient Advocacy",
    description: "NOVA's positive-review-to-advocacy automation — turns review.positive signals into advocacy/testimonial outreach.",
    triggers: ["review.positive"],
    emittedEvents: ["operational_events", "benchmark_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["agent.nova.patient_advocacy", "recommendation.advocacy_outreach"],
    actions: ["identify positive reviewers", "send advocacy invitation", "track testimonial conversion", "measure reputation lift"],
    intelligenceOutputs: ["advocacy conversion", "testimonial yield", "reputation lift"],
    aliceGroundingSurfaces: ["review sentiment", "patient value", "advocacy outcomes"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 180,
    observability: fullObservability
  },
  {
    id: "treatment_visualization",
    domain: "patient_influence",
    name: "Treatment Visualization Journey",
    description:
      "TVA's treatment education automation — generates and delivers treatment overview, expected outcome, recovery timeline, and FAQ for unscheduled high-value treatment plans, tracks engagement, and attributes treatment acceptance revenue.",
    triggers: ["treatment.visualization_required", "unscheduled high-value treatment plan detected"],
    emittedEvents: ["operational_events", "recommendation_events", "intelligence_events"],
    queueHandlers: ["agent.tva.treatment_visualization", "recommendation.treatment_education"],
    actions: ["generate treatment education", "deliver education media", "track engagement", "attribute acceptance revenue"],
    intelligenceOutputs: ["patient education readiness", "acceptance risk", "revenue influence"],
    aliceGroundingSurfaces: ["treatment plan value", "education engagement", "acceptance outcomes", "revenue attribution"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 60,
    observability: fullObservability
  },
  ...[
    ["video_confirmation", "Confirmation Video Journey", "appointment requires confirmation"],
    ["video_reminder", "Reminder Video Journey", "appointment reminder window reached"],
    ["video_recall", "Recall Video Journey", "recall due"],
    ["video_reactivation", "Reactivation Video Journey", "inactive patient over 12 months"],
    ["video_no_show_recovery", "No Show Recovery Video Journey", "appointment marked no-show"],
    ["video_post_visit", "Post Visit Recovery Video Journey", "procedure completed"],
    ["video_review_request", "Review Growth Video Journey", "satisfied patient detected"],
    ["video_referral_request", "Referral Growth Video Journey", "promoter patient detected"],
    ["video_membership", "Membership Enrollment Video Journey", "membership eligible patient detected"],
    ["video_treatment_acceptance", "Treatment Acceptance Video Journey", "treatment plan created"],
    ["video_vip_loyalty", "VIP Loyalty Video Journey", "high value patient loyalty moment"]
  ].map(([id, name, trigger]) => ({
    id,
    domain: "patient_influence" as const,
    name,
    description: `${name} selects the right patient journey video, tracks engagement, writes evidence, and attributes outcomes.`,
    triggers: [trigger],
    emittedEvents: ["video.generated", "video.sent", "video.opened", "video.viewed", "video.completed", "video.cta_clicked", "operational_events", "intelligence_events"],
    queueHandlers: [`video.${id}`, "n8n.video_delivery", "intelligence.video_recommendation"],
    actions: ["classify patient journey", "select video", "deliver video", "track engagement", "write attribution", "recommend next best action"],
    intelligenceOutputs: ["best send time", "best channel", "best journey", "expected revenue impact", "confidence score"],
    aliceGroundingSurfaces: ["patient journey", "delivery record", "engagement record", "revenue attribution", "mission control outcome"],
    replayRequired: true,
    retryEnabled: true,
    deadLetterRequired: true,
    slaMinutes: 90,
    dependencies: ["pms_sync", "n8n_delivery"],
    observability: fullObservability
  }))
];

export function getAutomationBlueprint(id: string) {
  return automationRegistry.find(blueprint => blueprint.id === id);
}
