-- Client Implementation OS
-- Adds repeatable onboarding, implementation, training, adoption, go-live, and customer success automation tables.

create table if not exists public.implementation_projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, client_name text not null, package_key text not null, implementation_owner text, current_phase text not null default 'signed', go_live_date date, risk_level text not null default 'normal', completion_percent integer not null default 0, status text not null default 'active', signed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.implementation_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, checklist_item_key text, task_type text not null, title text not null, owner text, owner_role text, status text not null default 'not_started', due_date date, evidence_type text, evidence_record_id uuid, evidence_status text not null default 'not_required', go_live_requirement boolean not null default false, completed_at timestamptz, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.implementation_blueprints (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, blueprint_key text not null, name text not null, package_key text not null, required_integrations text[] not null default '{}', required_data text[] not null default '{}', required_training text[] not null default '{}', required_workflows text[] not null default '{}', success_criteria text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, unique (organization_id, blueprint_key));
create table if not exists public.implementation_checklist_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, item_key text not null, stage text not null, section text not null, label text not null, task_type text not null default 'onboarding', default_owner_role text not null default 'implementation_owner', default_due_offset_days integer not null default 7, evidence_type text, go_live_requirement boolean not null default false, required boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, unique (organization_id, item_key));
create table if not exists public.client_onboarding_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, implementation_task_id uuid references public.implementation_tasks(id) on delete set null, item_key text not null, stage text not null default 'onboarding', section text not null default 'general', category text not null, label text not null, owner text, owner_role text not null default 'implementation_owner', due_date date, evidence_type text, evidence_record_id uuid, evidence_status text not null default 'required', go_live_requirement boolean not null default false, certification_gate text, sort_order integer not null default 0, required boolean not null default true, status text not null default 'not_started', completed_at timestamptz, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, unique (implementation_project_id, item_key));
create table if not exists public.integration_readiness_checks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, provider text not null, status text not null default 'not_started', last_checked_at timestamptz, failure_reason text, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.training_tracks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, track_key text not null, name text not null, persona text not null, required_modules text[] not null default '{}', created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, unique (organization_id, track_key));
create table if not exists public.training_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, training_track_id uuid references public.training_tracks(id) on delete set null, participant_name text not null, participant_email text, status text not null default 'assigned', assigned_at timestamptz not null default now(), completed_at timestamptz, certified_at timestamptz, metadata jsonb not null default '{}'::jsonb);
create table if not exists public.implementation_adoption_metrics (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, login_frequency integer not null default 0, workflow_usage integer not null default 0, alice_usage integer not null default 0, revenue_dashboard_usage integer not null default 0, video_usage integer not null default 0, treatment_acceptance_usage integer not null default 0, adoption_score integer not null default 0, classification text not null default 'low_adoption', measured_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.go_live_checklists (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, integrations_connected boolean not null default false, workflows_active boolean not null default false, templates_configured boolean not null default false, training_completed boolean not null default false, testing_passed boolean not null default false, certified boolean not null default false, certified_at timestamptz, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.customer_success_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, review_type text not null, status text not null default 'scheduled', summary text, scheduled_at timestamptz not null, completed_at timestamptz, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.client_health_rollups (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, health_score integer not null default 0, risk_score integer not null default 0, expansion_score integer not null default 0, adoption_score integer not null default 0, revenue_growth_score integer not null default 0, automation_usage_score integer not null default 0, support_activity_score integer not null default 0, measured_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create table if not exists public.client_operating_playbook_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, playbook_key text not null, playbook_name text not null, lifecycle_stage text not null, cadence text not null, objective text not null, success_metrics text[] not null default '{}', required_destinations text[] not null default '{}', created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, unique (organization_id, playbook_key));
create table if not exists public.client_operating_playbook_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, implementation_project_id uuid references public.implementation_projects(id) on delete cascade, playbook_key text not null, item_key text not null, stage text not null, section text not null, label text not null, owner text, owner_role text not null default 'customer_success', due_date date, status text not null default 'not_started', evidence_type text, evidence_record_id uuid, evidence_status text not null default 'required', completion_timestamp timestamptz, feeds_executive boolean not null default true, feeds_customer_success boolean not null default true, feeds_agency_crm boolean not null default true, feeds_evidence_os boolean not null default true, feeds_mission_control boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, unique (implementation_project_id, playbook_key, item_key));

create index if not exists idx_implementation_projects_org_phase on public.implementation_projects(organization_id, current_phase, updated_at desc);
create index if not exists idx_implementation_projects_go_live on public.implementation_projects(organization_id, go_live_date);
create index if not exists idx_implementation_tasks_project_status on public.implementation_tasks(implementation_project_id, status, due_date);
create index if not exists idx_implementation_tasks_checklist on public.implementation_tasks(implementation_project_id, checklist_item_key);
create index if not exists idx_implementation_checklist_templates_org_stage on public.implementation_checklist_templates(organization_id, stage, sort_order);
create index if not exists idx_client_onboarding_items_project_status on public.client_onboarding_items(implementation_project_id, status, due_date);
create index if not exists idx_client_onboarding_items_go_live on public.client_onboarding_items(implementation_project_id, go_live_requirement, status);
create index if not exists idx_integration_readiness_project_status on public.integration_readiness_checks(implementation_project_id, status);
create index if not exists idx_training_assignments_project_status on public.training_assignments(implementation_project_id, status);
create index if not exists idx_implementation_adoption_org_measured on public.implementation_adoption_metrics(organization_id, measured_at desc);
create index if not exists idx_go_live_checklists_project on public.go_live_checklists(implementation_project_id);
create index if not exists idx_customer_success_reviews_project on public.customer_success_reviews(implementation_project_id, scheduled_at);
create index if not exists idx_client_health_rollups_org_measured on public.client_health_rollups(organization_id, measured_at desc);
create index if not exists idx_client_operating_playbook_templates_org_stage on public.client_operating_playbook_templates(organization_id, lifecycle_stage);
create index if not exists idx_client_operating_playbook_items_project_status on public.client_operating_playbook_items(implementation_project_id, status, due_date);
create index if not exists idx_client_operating_playbook_items_feeds on public.client_operating_playbook_items(organization_id, feeds_executive, feeds_customer_success, feeds_evidence_os);

alter table public.implementation_projects enable row level security;
alter table public.implementation_tasks enable row level security;
alter table public.implementation_blueprints enable row level security;
alter table public.implementation_checklist_templates enable row level security;
alter table public.client_onboarding_items enable row level security;
alter table public.integration_readiness_checks enable row level security;
alter table public.training_tracks enable row level security;
alter table public.training_assignments enable row level security;
alter table public.implementation_adoption_metrics enable row level security;
alter table public.go_live_checklists enable row level security;
alter table public.customer_success_reviews enable row level security;
alter table public.client_health_rollups enable row level security;
alter table public.client_operating_playbook_templates enable row level security;
alter table public.client_operating_playbook_items enable row level security;

create policy "implementation_projects_service_all" on public.implementation_projects for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "implementation_tasks_service_all" on public.implementation_tasks for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "implementation_blueprints_service_all" on public.implementation_blueprints for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "implementation_checklist_templates_service_all" on public.implementation_checklist_templates for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "client_onboarding_items_service_all" on public.client_onboarding_items for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "integration_readiness_checks_service_all" on public.integration_readiness_checks for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "training_tracks_service_all" on public.training_tracks for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "training_assignments_service_all" on public.training_assignments for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "implementation_adoption_metrics_service_all" on public.implementation_adoption_metrics for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "go_live_checklists_service_all" on public.go_live_checklists for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "customer_success_reviews_service_all" on public.customer_success_reviews for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "client_health_rollups_service_all" on public.client_health_rollups for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "client_operating_playbook_templates_service_all" on public.client_operating_playbook_templates for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "client_operating_playbook_items_service_all" on public.client_operating_playbook_items for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
